### ISSUE TITLE
make icons links

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-plugin-fontawesome-icon#1]
Any way of adding a link option for the tag?
Since combining kirby tags doesn’t work.

**Comment by julien-gargot** [comment]
Didn’t thought about it before, but I will.

Could be great to just be able to add an `icon` parameter to the default link tag:
`(link:http://example.com text: Click here icon: camera-retro)`
to output:
`<a href="http://example.com"><i class="fa fa-camera-retro" aria-hidden="true"></i> Click here</a>`.

Plus some option to choose to displaying the icon before or after text?

**Comment by julien-gargot** [comment]
Update online. Better late than never.
